### ISSUE TITLE
Flaky test: cookie banner remembers user preference on subsequent visits

### ISSUE THREAD

**Issue by tamoreton** [infinityworks/govuk-frontend-starter#26]
Here's the code for the relevant test: https://github.com/infinityworks/govuk-frontend-starter/blob/f35321c0a76efd944e4daa6441530e12b2ee6fd7/tests/cookie-banner.spec.ts#L108-L128

The test occasionally fails, but then succeeds on a retry:

```
Error: expect(received).toBeTruthy()

Received: false

  115 |     expect(
  116 |       cookies.some((cookie) => cookie.name.includes("cookie_policy")),
> 117 |     ).toBeTruthy();
      |       ^
  118 |
  119 |     // Wait for transaction to complete before refreshing
  120 |     const confirmationMessage = page.getByText(
    at /home/runner/work/govuk-frontend-starter/govuk-frontend-starter/tests/cookie-banner.spec.ts:117:7
```

Here's a page snapshot at the time of the test failure:

```yaml
- region "Cookies on [name of service]":
  - alert:
    - paragraph:
      - text: You've accepted analytics cookies. You can
      - link "change your cookie settings":
        - /url: /cookies
      - text: at any time.
    - button "Hide cookie message"
- link "Skip to main content":
  - /url: "#main-content"
- banner:
  - link "GOV.UK":
    - /url: https://www.gov.uk/
    - img "GOV.UK"
- region "Service information":
  - link "Apply for a juggling license":
    - /url: /
  - navigation "Menu":
    - list:
      - listitem:
        - link "Get help with this service":
          - /url: /help
- paragraph:
  - strong: Alpha
  - text: This is a new service – your
  - link "feedback":
    - /url: "#"
  - text: will help us to improve it.
- main:
  - heading "Apply for a juggling license" [level=1]
  - paragraph:
    - link "Go to the start page":
      - /url: /apply-juggling-license/start
  - heading "JavaScript test" [level=2]
  - button "Show all sections"
  - heading "Writing well for the web , Show this section" [level=2]:
    - button "Writing well for the web , Show this section": Writing well for the web , Show
  - heading "Writing well for specialists , Show this section" [level=2]:
    - button "Writing well for specialists , Show this section": Writing well for specialists , Show
  - heading "Know your audience , Show this section" [level=2]:
    - button "Know your audience , Show this section": Know your audience , Show
  - heading "How people read , Show this section" [level=2]:
    - button "How people read , Show this section": How people read , Show
- contentinfo:
  - heading "Support links" [level=2]
  - list:
    - listitem:
      - link "Help":
        - /url: /help
    - listitem:
      - link "Cookies":
        - /url: /cookies
    - listitem:
      - link "Accessibility statement":
        - /url: /accessibility-statement
  - text: Built by the
  - link "Government Digital Service":
    - /url: https://www.gov.uk/government/organisations/government-digital-service
  - text: All content is available under the
  - link "Open Government Licence v3.0":
    - /url: https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
  - text: ", except where otherwise stated"
  - link "© Crown copyright":
    - /url: https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/
```
